[TIL-90] 기술학습 문제 리스트 구현
SOMA-TIL/TIL-Backend pull request #26
Opened 2024-07-24 14:04 UTC by dongyeon-0822

## 이슈 번호(링크)

[TIL-90](https://soma-til.atlassian.net/browse/TIL-90)

<br>

## 개요

- 기술학습 문제(Problem) 리스트 구현

<br>

## 내용

- Problem Entity, Repository 생성
- ProblemService, ProblemInfoDto 생성
- ProblemController, ProblemListResponse 생성

- Postman Response 결과 (테스트는 PathPermission에 "problem/**" 을 넣고 테스트함. )
<img width="741" alt="스크린샷 2024-07-24 오후 10 44 00" src="https://github.com/user-attachments/assets/ca11a51d-2f85-49a3-bfe7-19a24f63b42f">

<br>

## 리뷰어한테 할 말

- 페이징 객체가 jpa에 dependency가 있어, api 모듈에서 사용하지 않게 구현해볼 예정입니다. 리스트에서 페이징 기능 추가하고, 테스트 코드 작성할 예정입니다.
- 추가적인 Errorcode나 SuccessCode 작성이 필요하다면 말씀해주세요. 
- Dto나 Response 사용 부분에 수정할 부분이나 개선할 점이 있다면 알려주세요!

2024-07-24 14:30 UTC, doburn requested changes
PR 코멘트에서 언급하신 부분 위주로만 일단 리뷰해봤습니다! 🍉
Entity 작명같은 부분은 내일 같이 고민해보면 좋을것 같아요!

2024-07-24 14:30 UTC, doburn commented on til-domain/src/main/java/com/til/application/problem/ProblemService.java
> +    public List<ProblemInfoDto> getProblemList() {
```suggestion
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class ProblemService {

    private final ProblemRepository problemRepository;
    
    public List<ProblemInfoDto> getProblemList() {
```

P2: @Transactional(readOnly = true)를 서비스 레벨로 빼주고, 트랜잭션을 사용하는 메소드에 @Transactional을 따로 명시하는 방식은 어떠신가요?

2024-07-24 14:30 UTC, doburn commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +        return new ProblemListResponse(problemInfoDtoList);
```suggestion
public record ProblemInfoListResponse(
                                  List<ProblemInfoDto> problemInfoDtoList
) {

    public static ProblemInfoListResponse of(List<ProblemInfoDto> problemInfoDtoList) {
        return new ProblemInfoListResponse(problemInfoDtoList);
```

P3: 엔티티명인 `ProblemInfo` DTO명인 `ProblemInfoDto` 와 일관성을 맞추기 위해 `ProblemInfoListResponse`로 이름을 변경하는건 어떠신가요?
해당 이름이 너무 길면 `Info` 라는 단어를 제거하고 `Problem` `ProblemDto` `ProblemListResponse` 로 사용하는 방법도 괜찮을 것 같습니다!

2024-07-24 14:40 UTC, CodeDiary18 reviewed
P2: 사용자 화면 기준으로 보여지는 기술학습 문제 리스트 기능이여서  
제목, 난이도, 카테고리 부분은 필수로 제공하고  
실제 디테일한 문제(question), 정답(solution) 부분은 응답에서 제외시키면 좋을 것 같습니다!

2024-07-24 14:40 UTC, CodeDiary18 commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +                                  List<ProblemInfoDto> problemInfoDtoList
P3: 변수명이 현재 API response 반환될 때 묶이는 리소스명이어서 dto 같은 네이밍은 빠져도 괜찮을 것 같습니다!
```suggestion
                                  List<ProblemInfoDto> problemList
```

2024-07-24 14:59 UTC, dongyeon-0822 commented on til-domain/src/main/java/com/til/application/problem/ProblemService.java
> +    public List<ProblemInfoDto> getProblemList() {
넵 이 부분 조금 고민했는데, 제안해주신 방법이 더 좋을 것 같습니다! 
수정해놓겠습니다!

2024-07-24 15:05 UTC, dongyeon-0822 commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +        return new ProblemListResponse(problemInfoDtoList);
저도 이 부분을 어떻게 할지 고민했는데..
`info`를 빼고 `Problem` `ProblemDto` `ProblemListResponse` 이렇게 가는게 더 좋을 것 같습니다. 
이렇게 수정하겠습니다!

2024-07-24 15:06 UTC, CodeDiary18 commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +        return new ProblemListResponse(problemInfoDtoList);
controller 단에 있는 request나, response는 뒤에 네이밍을 ~Requset, ~Response로 통일시키면 좋을 것 같습니다😀

2024-07-24 15:29 UTC, dongyeon-0822 commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +                                  List<ProblemInfoDto> problemInfoDtoList
ProblemDTO는 상세화면에서도 같이 사용될 부분이여서 컬럼을 변경하기보다
dto안에 아래와 같이 메소드를 추가하는 방법으로 구현하면 될까요?
```java 
public static ProblemInfoDto forList(Problem problem) {
        return ProblemInfoDto.builder()
            .title(problem.getTitle())
            .score(problem.getScore())
            .build();
    }
```
아니면 아예 상세화면을 위한 dto와 리스트를 위한 dto를 따로 구현하는게 나을까요?

2024-07-24 15:32 UTC, CodeDiary18 commented on til-api/src/main/java/com/til/controller/problem/reponse/ProblemListResponse.java
> +                                  List<ProblemInfoDto> problemInfoDtoList
분리하는게 좋을 수도 있을 것 같습니다!  
상세 화면에서는 다른 부분에서 데이터를 엮어서 리스트와는 형태가 다른 데이터를 가져올 수도 있을 것 같아서 관심사를 분리해도 좋을 것 같습니다😀

2024-07-24 15:33 UTC, doburn reviewed
제가 요청드린 P2 변경점은 잘 반영된것 같습니다!
Approve는 @CodeDiary18 님이 체크하고 해주시면 될 것 같습니다!

2024-07-24 16:56 UTC, CodeDiary18 approved these changes

2024-07-25 00:26 UTC, doburn approved these changes

2024-07-25 06:43 UTC, merged